locations:
  - name: loc1
    location:
      position: { x: -0.5914, y: 0.4832, z: 0.0 }
      orientation: { x: 0.0, y: 0.0, z: -0.3196, w: 0.9475 }
  
  - name: loc2
    location:
      position: { x: -0.0318, y: -3.2284, z: 0.0 }
      orientation: { x: 0.0, y: 0.0, z: -0.2761, w: 0.9611 }

  - name: loc3
    location:
      position: { x: -0.8151, y: -4.7575, z: 0.0 }
      orientation: { x: 0.0, y: 0.0, z: -0.4055, w: 0.914 }
  
  - name: loc4
    location:
      position: { x: -0.8146, y: -4.7472, z: 0.0 }
      orientation: { x: 0.0, y: 0.0, z: -0.941, w: 0.3381 }

Bin:
  location:
    position: { x: 0.6827, y: 1.3056, z: 0.0 }
    orientation: { x: 0.0, y: 0.0, z: 0.3327, w: 0.943 }

Entrance:
  location:
    position: { x: -0.6682, y: 0.5017, z: 0.0 }
    orientation: { x: 0.0, y: 0.0, z: -0.1572, w: 0.9875 }
